### ISSUE TITLE
Mac app is not notarized

### ISSUE THREAD

**Issue by joeljfischer** [stacks-task-manager/stacks#1]
To allow the app to be opened on Macs without jumping through hoops, it needs to be notarized.

**Comment by synapse** [comment]
Hey @joeljfischer can you check on the latest version [0.2.2](https://github.com/stacks-task-manager/stacks/releases) if this is fixed?

**Comment by joeljfischer** [comment]
Unfortunately not. See the error message I'm getting when I attempt to open the app.
![Screen Shot 2020-04-15 at 11 31 58 AM](https://user-images.githubusercontent.com/1767063/79356300-c59da700-7f0c-11ea-9044-6fac1afaf0a3.png)

**Comment by synapse** [comment]
@joeljfischer can you please check again with the latest version v0.2.4

**Comment by joeljfischer** [comment]
This is resolved!
