### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by MeloncholyShiro** [stacks-task-manager/stacks#10]
Whis is horror, really.
![image](https://user-images.githubusercontent.com/44039577/80432895-23af8e80-88fe-11ea-8ab7-cd27cddf0b0f.png)
Can you make like whis? Or something similar, horizontal scrolling is very inconvenient
![image](https://user-images.githubusercontent.com/44039577/80432971-522d6980-88fe-11ea-9271-d3d320e72fe1.png)

**Comment by synapse** [comment]
Hello @MeloncholyShiro, thanks for your feedback. In a kanban, layout columns go one beside the other (horizontally) otherwise we would have rows. 
In a future release, we'll create also a vertical layout 😉 .

**Comment by synapse** [comment]
Hey @MeloncholyShiro the new version of Stacks (currently in beta) has multiple new views including list view and table view.

**Comment by synapse** [comment]
Hey @MeloncholyShiro  check out the latest version that was just released 😉
