### ISSUE TITLE
Separate search for Archives vs Active Tasks

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#100]
**Is your feature request related to a problem? Please describe.**

90% of the time when searching I am interested in my active (un-archived) tasks, and search results from the Archives just clutters up my results and makes it harder to find what I'm looking for.  The other 10% of the time I want to include the Archives in my search, or perhaps just search the Archives without searching the active tasks.

**Describe the solution you'd like**
I would like basic search to exclude the Archives, but with an easily accessed option to include the Archives, or to search only within the Archives.

**Describe alternatives you've considered**
I use an entirely different Workspace for archiving, and don't really use the built-in Archives at all, but this is not very efficient.

**Comment by synapse** [comment]
@mbrock321  Would it be ok to have an option in the preferences to switch back and forth between searching in the archives or active tasks?

**Comment by mbrock321** [comment]
Sure, that ought to do the trick.  It might be useful to have 3 options -- search Actives-only, Archives-only, or Both -- which would preserve the current functionality if there are those that prefer it as is.

**Comment by synapse** [comment]
Hey @mbrock321 this option was added starting from [V1.6.0 Beta 9](https://github.com/stacks-task-manager/stacks/releases/tag/v1.6.0-b9). Check out the new Search section in the General Preferences tab

**Comment by mbrock321** [comment]
Hi @synapse -- I had a quick look at this feature in 1.6.0.  The way it is set up with the checkboxes in the preferences makes sense to me, but I don't find the search is working as expected.  

If just the "Active tasks" checkbox is on, it finds matches in both my active tasks and archives.

If just the "Archived tasks" checkbox is on, it doesn't find matches in the archives or anywhere else.

(And when I first started the new version, it wasn't returning any search results at all.  When I pulled up the preferences all the options were checked.  Only after I started playing around with them did I start seeing some search results.)

Cheers,
--Michael

**Comment by synapse** [comment]
Hey @mbrock321 yes for some reason the updated version does not search any more. I'm already looking into it and will do another hot-fix release first thing tomorrow

**Comment by synapse** [comment]
@mbrock321 this should be fixed in 1.6.1, can you confirm that it's working?

**Comment by mbrock321** [comment]
@synapse -- Searching gives some results when I start up with 1.6.1, which is good, but as for the other search issue, the problem has just been inverted.

Now, if only the "Archived tasks" checkbox is selected, it finds matches in both active tasks and archives.
If only the "Active tasks" checkbox is selected, it doesn't find matches in the active tasks or anywhere else.

**Comment by synapse** [comment]
Should be fine in 1.6.2 @mbrock321

**Comment by mbrock321** [comment]
I've only tested with archives/actives, since those are what I principally use, and they seem to be working well.  
Thanks @synapse -- this will be a very helpful improvement for me...

**Comment by mbrock321** [comment]
@synapse -- now that you have a structure in place for constraining the search targets, would it be possible to add searching the text inside tasks as an option?

That would be amazing!  Right now, I think you can only search on task title text.

**Comment by synapse** [comment]
Fixed in [v1.9.1](https://github.com/stacks-task-manager/stacks/releases/tag/v1.9.1)
Since 1.9.0 search also works in task description
