### ISSUE TITLE
Copy/Move - doesn't remember Destination Stack correctly

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#104]
**Describe the bug**
When using Copy/Move task command, with the option to "Keep selected options", most of the selected options are remembered correctly when the command is next used, but the "Destination Stack" appears to always get reset to the first stack in the Project where the last task was moved.

**To Reproduce**
1. Right-click on Task, select "Copy or Move..." from the pop-up menu
2. Make sure "Keep selected options after Move/Copy" are selected.
3. for "Destination Stack" choose a target stack that is not the first stack in the drop-down list
4. Move the task
5. Repeat the steps with another task
6. The Destination Stack default value will be set to whatever Stack is at the top of the drop-down list, not to the Stack that was previously chosen
7. Same issue affects Copying a task

**Expected behavior**
Destination Stack default value should remain set to the last chosen Stack when command was previously used.

**Desktop (please complete the following information):**
OS: OSX 10.14.6, Mojave
Stacks Version 1.5.6

**Comment by synapse** [comment]
@mbrock321 fixed, available in 1.7.2

**Comment by mbrock321** [comment]
Just gave this a quick test, and it seems to work as expected now -- thanks for the fix!
