### ISSUE TITLE
When deleting a folder, the document tree for it doesn't delete

### ISSUE THREAD

**Issue by user8446** [stacks-task-manager/stacks#106]
Hi,

When deleting a folder, the document tree for it doesn't delete. 

To reproduce:
1. Delete a folder
2. Import new
3. The new will be merged into the deleted non-existent documents from the deleted folder

Expected behavior:
1. The new should have a new clean document tree

Stacks v1.7.0

Thank you

**Comment by synapse** [comment]
@user8446 fixed and available in 1.7.2

**Comment by user8446** [comment]
Thank you for the fix!
