### ISSUE TITLE
Hi, is it possible to make the website address in 'Contacts' a hyperlink to the actual website?

### ISSUE THREAD

**Issue by Kernow66** [stacks-task-manager/stacks#108]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by synapse** [comment]
Hi @Kernow66 should be fixed in [v1.7.4](https://stacks.rocks/updates/#version-1.7.4)

**Comment by Kernow66** [comment]
Wow that was quick! Thank you.
