### ISSUE TITLE
Allow Dates in Task Title

### ISSUE THREAD

**Issue by doctopus** [stacks-task-manager/stacks#11]
**Is your feature request related to a problem? Please describe.**
Dates with / get converted in to markdown italics. 5/5/2020 becomes 552020

**Describe the solution you'd like**
Allow writing dates in title

**Comment by synapse** [comment]
To fix this implies that italic styling has to have a space before and after the word (_ = space) `_ /italic/_` and won't be able to have multi spaced words styled without wrapping each work with slashes. @doctopus can't you just use different date formats? (e.g. 5-2-2020 or 5.2.2020)
