### ISSUE TITLE
Ability to filter tasks

### ISSUE THREAD

**Issue by vicryt8** [stacks-task-manager/stacks#112]
**Describe the solution you'd like**
Filter options for tasks:
- Board View: Filter by tags, assignee, priority
- List View: Filter by tags, assignee, priority
- Table View: Filter by assignee
- Calendar View: Filter by tags, assignee, priority
- Dashboard View: Filter by tags, assignee, priority

**Comment by synapse** [comment]
Hey @vicryt8 have you tried the Project filters which you can find on the bottom right corner in the latest version?
