### ISSUE TITLE
Workspace Statuses: Editing Tag Color

### ISSUE THREAD

**Issue by T1mMc** [stacks-task-manager/stacks#113]
Changing the color of an existing Workspace Status Tag does not update the tag color.    This does work if you change the color of a Project Status Tag.

**To Reproduce**
1.  Click on Project Preferences
2.  Click on Statuses
3. Select an existing Tag under Workspace Statuses
4.  Change the color
5.  Select the Checkmark to save
6.  Note the color of the tag has not updated.

**Expected behavior**
The color of tag should update to reflect the color change like it does if you are editing a Project Status tag. 

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser:  Chrome

**Comment by synapse** [comment]
Hey @T1mMc which version are you using? Seems to be working on the latest version 1.8.2
![2022-03-28 19 13 20](https://user-images.githubusercontent.com/71137/160451955-69d627e5-84c8-4939-ab3e-a82ecd766ea9.gif)

**Comment by synapse** [comment]
@T1mMc found the bug, it is on the global Statuses

**Comment by T1mMc** [comment]
I was on the latest.   I am glad you were able to locate it.   thanks for your time!
