### ISSUE TITLE
Export Functionality

### ISSUE THREAD

**Issue by Robert2127** [stacks-task-manager/stacks#119]
Hi,
I'm very new to Stacks as I just downloaded it last week and I've been playing around with it some.  I've not yet purchased the Pro version as I need one more piece of functionality that may be included, but which I've not found yet.

As a middle-manager, I have employees who are working on projects for me for which I need to track the project progress and it seems this application will work fine - but I also have to report to my boss the status of the various projects I'm managing.  As such, I need to create bi-weekly reports.  Any items that I need to present to my boss, I'm flagging with a #Status tag.

Is there any way to export ALL tasks with the #Status across all projects to a Word document or a spreadsheet?

**Comment by Robert2127** [comment]
Thanks!

**Comment by synapse** [comment]
@Robert2127 you can check it out in the current [beta version](https://github.com/stacks-task-manager/stacks/releases/tag/v1.9.0-b12)
