### ISSUE TITLE
Cannot delete a task from the Archive

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#121]
**Describe the bug**
Not possible to delete a task in Archive view.

**To Reproduce**
1. Go to the Archive View
2. Click on a task
3. Use keyboard command (Mac) cmd-backspace to delete.
4. Dialogue pops up "Are you sure you want to delete this task? ... Yes/No"
5. Click on "Yes"
6. Nothing changes

**Expected behavior**
the selected task should be deleted.

**Desktop (please complete the following information):**
OSX 10.14.6

**Comment by synapse** [comment]
Fixed in [v1.9.1](https://github.com/stacks-task-manager/stacks/releases/tag/v1.9.1)
