### ISSUE TITLE
Stack automation removes all tags from task

### ISSUE THREAD

**Issue by ikrz** [stacks-task-manager/stacks#122]
**Describe the bug**
Stack automation clears all tags and set selected tag, even when clear tags is not selected.

**To Reproduce**
1. Open Stack and select "Manage Automation..."
2. In Move tab select "Newly added"
3. In Tags tab are two options, either add tags or select "Clear all tags". It is evident from instruction, that you have to choose one of these two options, and other is then disabled. Select a Tag. Close.
4. Create some task, assign some Tags, different as selected one.
5. Move this task to the stack, it will clear all tags on task and assign stack selected tag as only tag.

**Expected behavior**
Should leave tags intact, since this option is not selected, and only add the stack selected tag to the task.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Version 1.8.3

**Comment by synapse** [comment]
Fixed in [v1.9.1](https://github.com/stacks-task-manager/stacks/releases/tag/v1.9.1)
