### ISSUE TITLE
Stacks 1.9.0 not starting

### ISSUE THREAD

**Issue by ikrz** [stacks-task-manager/stacks#124]
**Describe the bug**
Yesterday Stacks worked fine, today after fresh computer start it does not work.

**To Reproduce**
1. Click on Stacks icon 
2. Nothing happens

**Expected behavior**
Should start the app

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser Firefox 101.0 (64-bit)
 - Version Not sure, I have a suspicion it did some autoupdate since yesterday.

**Additional context**

Processes have started, but no GUI: 
ps aux | grep stacks
ikriznar   23684  6.2  0.8 21742940 129924 ?     Sl   08:34   0:00 /snap/stacks-task-manager/68/stacks-task-manager --no-sandbox --enable-crashpad
ikriznar   23756  0.0  0.2 17173120 46880 ?      S    08:34   0:00 /snap/stacks-task-manager/68/stacks-task-manager --type=zygote --no-zygote-sandbox --no-sandbox --enable-crashpad --enable-crashpad
ikriznar   23757  0.1  0.2 17173120 47084 ?      S    08:34   0:00 /snap/stacks-task-manager/68/stacks-task-manager --type=zygote --no-sandbox --enable-crashpad --enable-crashpad
ikriznar   23781  2.0  0.5 17406084 94028 ?      Sl   08:34   0:00 /snap/stacks-task-manager/68/stacks-task-manager --type=gpu-process --no-sandbox --enable-crashpad --enable-crash-reporter=cd740471-c348-404a-8b4f-fa6cd5b1ce05,no_channel --user-data-dir=/home/ikriznar/snap/stacks-task-manager/68/.config/stacks-app --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,8089753216993626532,1977228482810124146,131072 --disable-features=SpareRendererForSitePerProcess
ikriznar   23784  0.2  0.3 17238796 56548 ?      Sl   08:34   0:00 /snap/stacks-task-manager/68/stacks-task-manager --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --enable-crashpad --enable-crash-reporter=cd740471-c348-404a-8b4f-fa6cd5b1ce05,no_channel --user-data-dir=/home/ikriznar/snap/stacks-task-manager/68/.config/stacks-app --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,8089753216993626532,1977228482810124146,131072 --disable-features=SpareRendererForSitePerProcess --enable-crashpad
ikriznar   23788  0.6  0.5 25806148 92452 ?      Sl   08:34   0:00 /snap/stacks-task-manager/68/stacks-task-manager --type=renderer --enable-crashpad --enable-crash-reporter=cd740471-c348-404a-8b4f-fa6cd5b1ce05,no_channel --user-data-dir=/home/ikriznar/snap/stacks-task-manager/68/.config/stacks-app --app-path=/snap/stacks-task-manager/68/resources/app.asar --enable-sandbox --no-sandbox --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --launch-time-ticks=3662655174 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,8089753216993626532,1977228482810124146,131072 --disable-features=SpareRendererForSitePerProcess
ikriznar   23794  0.3  0.5 25796084 84288 ?      Sl   08:34   0:00 /snap/stacks-task-manager/68/stacks-task-manager --type=renderer --enable-crashpad --enable-crash-reporter=cd740471-c348-404a-8b4f-fa6cd5b1ce05,no_channel --user-data-dir=/home/ikriznar/snap/stacks-task-manager/68/.config/stacks-app --app-path=/snap/stacks-task-manager/68/resources/app.asar --enable-sandbox --no-sandbox --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --launch-time-ticks=3662661961 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,8089753216993626532,1977228482810124146,131072 --disable-features=SpareRendererForSitePerProcess
ikriznar   23815  1.8  0.6 25868324 112060 ?     Sl   08:34   0:00 /snap/stacks-task-manager/68/stacks-task-manager --type=renderer --enable-crashpad --enable-crash-reporter=cd740471-c348-404a-8b4f-fa6cd5b1ce05,no_channel --user-data-dir=/home/ikriznar/snap/stacks-task-manager/68/.config/stacks-app --app-path=/snap/stacks-task-manager/68/resources/app.asar --no-sandbox --no-zygote --no-sandbox --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=6 --launch-time-ticks=3662672734 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,8089753216993626532,1977228482810124146,131072 --disable-features=SpareRendererForSitePerProcess --enable-crashpad
ikriznar   23870  0.0  0.0  14692  2488 pts/0    R+   08:34   0:00 grep --color=auto stacks

If I press Stacks icon again, it starts another bunch like this.
If I kill all stacks processes and start stacks-task-manager from command line I get:

$ stacks-task-manager 
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/Stacks Linux/resources/app-update.yml'
(node:26481) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Stacks Linux/resources/app-update.yml'
(Use `stacks-task-manager --trace-warnings ...` to show where the warning was created)
(node:26481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Stacks window opens and pretends, there is no workspace and asks to load Demo data. I say no. Fortunately my stacks data looks intact.

Some more info:

ls /opt/Stacks\ Linux/resources
app.asar

Would be nice to have a workaround as soon as possible.

**Comment by ikrz** [comment]
snap:
stacks-task-manager  1.8.3                       67     latest/stable    stackstaskmanager  disabled
stacks-task-manager  1.9.0                       68     latest/stable    stackstaskmanager  -

**Comment by ikrz** [comment]
Found a workaround: 
$ sudo snap revert stacks-task-manager
stacks-task-manager reverted to 1.8.3

Reverted to version 1.8.3 and Stacks works fine now.
Looks like Stacks version 1.9.0 gives problems.

**Comment by synapse** [comment]
On it, thanks @ikrz

**Comment by synapse** [comment]
@ikrz should be fixed in [v1.9.1](https://github.com/stacks-task-manager/stacks/releases/tag/v1.9.1)
