### ISSUE TITLE
1.9.1 Clicking on top of a stack no longer selects the stack

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#126]
**Describe the bug**
When clicking on the grey area near the title at the top of a stack, the stack is no longer selected.

**To Reproduce**
1.click on a stack in the grey area beside the title
2. The stack does not become highlighted and is not selected for e.g. keyboard commands.

**Expected behavior**
The stack should become highlighted and be the target for keyboard commands.

**Desktop (please complete the following information):**
OSX 10.14.6

**Comment by synapse** [comment]
It was removed due to the fact that it hasn't had any important usage, will be readded in next version

**Comment by mbrock321** [comment]
I typically select the stack in this way when I want to collapse or expand it using the keyboard shortcuts.

I see it's possible to click on a task, and those expand/collapse keys are still active, so I suppose I can do that as an alternative.  But it seems like inconsistent UI design not to be able to click on a stack to select it, when I'm trying to use a command that operates on the stack, and when it does highlight as a selection under other circumstances -- i.e. when clicking on a task, or when using the arrow keys to move between stacks.

**Comment by mbrock321** [comment]
This works to select a stack, but now the arrow keys no longer work to move from task to task or between stacks.

**Comment by synapse** [comment]
Fixed in version [1.9.4](https://github.com/stacks-task-manager/stacks/releases/tag/v1.9.4)
