### ISSUE TITLE
actual markdown support

### ISSUE THREAD

**Issue by DAmNRelentless** [stacks-task-manager/stacks#128]
Good job on this project, I really like it. This is just a feature request and a suggestion. If it sounds harsh, it might be due to a language barrier. Sorry in advance.

**Is your feature request related to a problem? Please describe.**
Might be related to https://github.com/stacks-task-manager/stacks/issues/38 but for notepads.

There are some places where markdown is not fully supported or not working.
The notepad is nice already but it doesn't feel very fluent if you need to use your mouse to get specific formatting that would otherwise work in markdown with specific operators.
Things that don't work but would be very nice to have without using the mouse:
```
  ~~ - strike-through
  - [ ] - checkbox (will convert to a bullet list instead)
  --- - line separator
  `something` - inline code with
  ``` - codeblocks
```

Interestingly, this all works fine in a project board within the description of a task.

Another issue that is probably due to the unsupported operators and no actual markdown is that valid markdown won't be converted to the notepad format when pasting it in. So something like this is a valid markdown:
```md
## Main Branch
- foo bar
    - lorem
    - ipsum
- foobar
- foo bar
- refactor `render` method in  `RendererRegistry`

### Todo
- [ ] some checklist 1
- [ ] some checklist 2

### Striking
~~This is strike-through formatting.~~
```
but the notepad will not accept it. You need to go to each line manually and adjust the formatting.

Another place that's missing some markdown features is a task's title. If you're on a project board and create a new task in a stack, you can style the task's title by e.g. making it bold or italic but you can't put code there.
If you want to have a task that's called: "refactor `ClassWhatever#render`", this will create a tag called "render" and the title will not include the code block, and the word "render" will be gone.

**Describe the solution you'd like**
Maybe a better markdown interpreter would be useful or adapt to GitHub markdown. Of course, it's a lot more responsive with live rendering but that is not necessary if you have a good markdown editor with a preview.

A whole other way would be a custom importer so you can import markdown files and they are automatically converted to the notepad format.

**Describe alternatives you've considered**
Alternatives are using the notepad functionality of other apps like Obsidian which does that very well (maybe a good inspiration) but I would like to keep everything in Stacks so I usually manually adjust the formatting there.

**Additional context**
How it should look:
![](https://i.imgur.com/vFQUzJ6.png)
How it actually looks like:
![](https://i.imgur.com/U0xcSQQ.png)

**Comment by synapse** [comment]
@DAmNRelentless should be added in [1.9.2](https://github.com/stacks-task-manager/stacks/releases/tag/v1.9.2)

**Comment by synapse** [comment]
The notepad is not a markdown editor, thus it has some limited md interpreting options. We're planning to change this WYSIWYG editor to a full markdown one

**Comment by DAmNRelentless** [comment]
That would be lovely!

**Comment by synapse** [comment]
I'm gonna close this one out until then
