### ISSUE TITLE
tag and status issues

### ISSUE THREAD

**Issue by DAmNRelentless** [stacks-task-manager/stacks#129]
**Describe the bug**
If I open a project board, go to the project settings and to the `Tags` or `Statuses` sub-menu, I can't delete any of them.
It asks me if I am sure to delete them and it doesn't matter if I press Yes or No, nothing will happen. Oddly enough, if I add new Workspace Tags, they will be listed as Project Tags as well and I can't delete those either.
I can also create duplicate tags with the exact same name and color and it will add them as well.

I also find it weird that using `#foo` in a task title will add a new tag called `foo` to my project. This quickly fills up my project tags so it would be nice if that could be disabled somewhere. I often use stuff like "refactor "MyClass#methodBar()` in my tasks and I then can't delete them.

One more issue I am having is the way you have to color stacks. If you want to give a project board column (stack) a color, you have to create a tag for it. Why is that? I only want to assign a color. This is pretty inconvenient if you have a lot of tags already and you need to scroll through even more tags when assigning them to tasks because there is a tag for each column too.

**To Reproduce**
1. Open a project board
2. Go to the project settings
3. Go to the Tags sub-menu
4. Create a project tag
5. Create a workspace tag with the same color and name as the project tag
6. Try to delete tags

**Expected behavior**
Tags should not accept duplicates, workspace tags shouldn't be moved to project tags, tags should be removable, there should be a setting to disable the automatic creation of tags when using `#` in tasks or ignore those automation symbols when used within code, Stacks should not require their own tags in order to be colored

**Screenshots**
Tags like `crash`, `bug` and `enhancement` are workspace tags but show up in project tags. All tags starting with a capital letter are just for column/stacks coloring. All tags ending with an apostrophe are auto-created because I used a description like "refactor `MyClass#fooBar()`"
![](https://i.imgur.com/BF8goB2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Edge
 - Version: Stacks 1.9.2

**Comment by DAmNRelentless** [comment]
What about the other mentioned points? Should I create separate issues for those?

**Comment by synapse** [comment]
hey @DAmNRelentless no need, already on it
