### ISSUE TITLE
Links to websites and local files no longer open after upgrade to 1.9.x

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#131]
**Describe the bug**
Previously it was possible to include a link in the form
   file:///Volumes/<diskname>/<pathname>/<filename>
and clicking on this link would open the local file.

This no longer seems to work.

Even a simple link like this
`   [https://www.google.com](url)`
doesn't seem to be clickable.

Does this still work?

**Desktop (please complete the following information):**
OSX 10.14.6

**Comment by mbrock321** [comment]
A couple more notes:

In 1.9.3, the new markedown syntax doesn't seem to work as noted above, but the old link synax does, so the following text in a description will still jump to the web-page:
 
`
<a href="https://www.google.com/">Google Search</a>`

However
   `
<a href="file:///Volumes/path-to-local-file">Local File</a>`

doesn't seem to work to access a local file.

**Comment by synapse** [comment]
@mbrock321 unfortunately the markdown parser rejects any other protocol than `http`. To fix this I've added a new format for adding links to local files including a new button in the editor toolbar which helps you link to a file quicker then writing it by hand

This `file:///path/to/file`  becomes `</!/path/to/file>`

**Comment by mbrock321** [comment]
Hmm, I'm trying to get that to work, following the MArkdown Cheatsheet guidelines, but it doesn't seem to be working.  

In the following, the web link works, but the file link doesn't:

`[This is a document link](</!/Volumes/MacHD1-Media/testlink/test1.rtf>)

[Google Search](https://www.google.com)`

Can you tell me if the format of the file link looks correct?

**Comment by mbrock321** [comment]
Oh -- I see, this functionality was newly added in version 1.9.4 -- tested there, and it works.  Thanks for the quick fix!
