### ISSUE TITLE
Long Tag Name Overflow

### ISSUE THREAD

**Issue by loikawhaticando** [stacks-task-manager/stacks#133]
**Long Tag Name Overflow Description**
Very long tag names do not line break, truncate, or otherwise do the proper thing visually. They just overflow their UI element

**To Reproduce**
1. Create a very long tag name and assign it to a task. 
2. Observe the places in the UI where the tag overflows its UI element. In task details the main body isn't a fixed width so the long tag name will "push" the contents outside of the bounding element to the left and right. In Dashboard view, "Tags Overview", the long names overflow their UI element and overflow onto the next tag element.

**Expected behavior**
Generally, rather than overflow or increase the size of the UI element, long names should be truncated with an elipsis and the full name visible on mouse hover. In cases where the full tag name is necessary (like the dashboard?) the UI should be able to handle the long name. Obviously I could just use shorter tag names but I needed somewhere to put a long text string to categorize tasks and this was the least obtrusive place I could find.

**Screenshots**

![image](https://user-images.githubusercontent.com/2561017/177420359-3fd79f01-9390-431f-abeb-c12ee01bf5c6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Vivaldi
 - Version: 1.9.7

**Comment by synapse** [comment]
hey @loikawhaticando this should be fixed since v1.9.8

**Comment by loikawhaticando** [comment]
Thanks!
