### ISSUE TITLE
Dashboard Doesn't Display Workspace Tags?

### ISSUE THREAD

**Issue by loikawhaticando** [stacks-task-manager/stacks#134]
**Dashboard Doesn't Display Workspace Tags?**
The dashboard doesn't display workspace tags, only project tags.

**To Reproduce**
1. Create a workspace tag, assign it to a task.
2. Open the dashboard for that project.

**Expected behavior**
The project AND workspace tags are displayed in the dashboard under Tags Overview.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Vivaldi
 - Version: 1.9.7

**Comment by synapse** [comment]
Hey @loikawhaticando this should be fixed as of v1.9.8

**Comment by loikawhaticando** [comment]
Thanks!
