### ISSUE TITLE
Urls with # not handled correctly

### ISSUE THREAD

**Issue by posinautinc** [stacks-task-manager/stacks#135]
**Describe the bug**
1. Urls with a hash (for in page bookmarking) entered into the description field are not handled correctly.
2. Example "https://www.alphavantage.co/documentation/#latestprice" gets converted to "https://www.alphavantage.co/documentation/<#Unknown>"

**To Reproduce**
1. Create a new task
2. Edit the task and paste 'https://www.alphavantage.co/documentation/#latestprice' into the description
3. Exit/save the task
4. Edit the task and view the description field
5. Description field contains 'https://www.alphavantage.co/documentation/<#Unknown>'

**Expected behavior**
1. Hash in url should not be modified.

**Screenshots**
1. Before and after screens attached.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 1.9.8

**Additional context**
![20220719_Stacks_url_hash_bug_02](https://user-images.githubusercontent.com/75622602/179817053-f4f65b10-6076-4df8-a92c-101e0452550e.png)
![20220719_Stacks_url_hash_bug_01](https://user-images.githubusercontent.com/75622602/179817058-8865e1ca-3ed8-4cc6-b304-16e02fc09d7f.png)

**Comment by synapse** [comment]
@posinautinc fixed in v1.9.9

**Comment by posinautinc** [comment]
Thank you for the quick fix @synapse.
