### ISSUE TITLE
Native OS Title Bar

### ISSUE THREAD

**Issue by g0nz4rth** [stacks-task-manager/stacks#136]
**Is your feature request related to a problem? Please describe.**
No, it's not.

**Describe the solution you'd like**
It would be great if we could use native OS title bars on Stacks. I use Elementary OS (ubuntu-based Linux distro) and Stacks looks like an alien application on my distro, with a title bar that differs from all of my other apps.

**Describe alternatives you've considered**
I haven't thought of any other alternative.

**Comment by synapse** [comment]
@g0nz4rth fixed in v1.9.9
