### ISSUE TITLE
Stacks Reveal Current Workspace Bug

### ISSUE THREAD

**Issue by Saltomar** [stacks-task-manager/stacks#137]
Clicking on:

1. Click on Top left menu icon
2. Click on 'Workspaces' 
3. Click on 'Reveal Current Workspace'

...result in a loop that opens hundreds of the same folders and crashes windows in that way.

Not sure if someone has the same problem. Using (still) free version of Stacks under Windows 10 Pro.

System:

Windows 10 Pro with latest updates.

Cheers.

**Comment by synapse** [comment]
Hey @Saltomar usually Windows is opening Explorer and keeps it minimized on the bottom bar which may look like nothing happens. Could be that wha you're experiencing? Could you maybe upload a quick video capture?

Thanks

**Comment by Saltomar** [comment]
After upgrading to 1.9.9, the problem is gone.

Cheers,
