### ISSUE TITLE
not working check update

### ISSUE THREAD

**Issue by AlexeyKolodchenko** [stacks-task-manager/stacks#14]
**Describe the bug**
Not working check update version the application

**To Reproduce**
1. Go to menu Stacks
2. Click on Check update
3. And silent........

**Expected behavior**
I want to see a notification about a new version of the app preferably check it automatically

**Screenshots**
no screenshots

**Desktop (please complete the following information):**
 - macOS Catalina
 - Version [e.g. 0.2.5]

**Comment by synapse** [comment]
Hi @AlexeyKolodchenko , have you tried with one of the newest versions 0.2.7 or the latest 0.2.8?
