### ISSUE TITLE
Option to activate the top right window icons for window control

### ISSUE THREAD

**Issue by Saltomar** [stacks-task-manager/stacks#140]
**Is your feature request related to a problem? Please describe.**
There's no top bar containing windows commands (Maximize, minimize, etc). It's kind of tedious to always need to right-click and chose the window command. 

**Describe the solution you'd like**
Options to enable app window control icons to appear in the top right corner.

**Describe alternatives you've considered**
+ AND/OR key shortcuts. 

**Additional context**

**Comment by Darthagnon** [comment]
"Native title bar" was supposed to be enabled in Stacks v1.9.9, but it doesn't work on Windows. There is no titlebar with window controls.

There doesn't seem to be a config option to re-enable the non-native window controls either.

**Comment by Darthagnon** [comment]
@synapse solved in v1.9.10

**Comment by Saltomar** [comment]
@synapse 

Confirmed, thanks a lot! Case closed.
