### ISSUE TITLE
Quick Search function not working (ctrl+k)

### ISSUE THREAD

**Issue by cobbinaloic** [stacks-task-manager/stacks#146]
**Describe the bug**
The Quick search function (ctrl+k) can't find anything at all. It just keeps searching forever.

**To Reproduce**
1. Go to 'Quick Search box'
2.  'Type in the task you are searching for, knowing that you've already created that task'
3. The search is ongoing but nothing shows up as a result
4. Meanwhile, when you manually scroll down, you can see the task does exist

**Expected behavior**
I am expecting the "searched task" to show up when I type in the the search box.

**Desktop (please complete the following information):**
 - OS: MXLInux 21 KDE

**Comment by synapse** [comment]
Hey @cobbinaloic have you tried rebuilding the search cache? There's a menu item under the Help section to do it.
Let me know if works afterwards?

**Comment by cobbinaloic** [comment]
Yes I did  try rebuilding the search cache earlier on before even reporting
the issue. But just to be sure I decided to try it again a couple of times
and the problem persists.

**Comment by synapse** [comment]
Do you see a file named `search.db` in your workspace folder? @cobbinaloic

**Comment by cobbinaloic** [comment]
Sorry eventually I formatted the whole PC. The problem is gone. I don't
know what was really causing it.
