### ISSUE TITLE
Search doesn't work with letter 'x'

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#152]
**Describe the bug**
Searches involving the letter 'x' do not return expected results

**To Reproduce**
1. Create a task with a title containing an 'x', ie. "sax searchme"
2. initiate a search with cmd-K and type in "sax"
3. the newly created task does not appear in the search list
4. type "searchme" in the search bar
5. the newly created task appears as "sa searchme"
6. Same problem with e.g. "max searchme" or with "sax searchme" in the Description rather than the title

**Expected behavior**
In example above, the searches in steps 2 and 4 should both return the results "sax searchme"

**Screenshots**
Added 3 screenshots demonstrating the problem

**Desktop (please complete the following information):**
OSX 10.14.6
Stacks v 1.9.12

**Additional context**
![Screen Shot 2022-09-13 at 10 58 34 AM](https://user-images.githubusercontent.com/85841371/189978865-348d6a1b-e98f-4047-a6bd-b2211b242b4e.png)
![Screen Shot 2022-09-13 at 10 58 24 AM](https://user-images.githubusercontent.com/85841371/189978872-a756aacc-07e1-4524-a8c6-17191ea149aa.png)
![Screen Shot 2022-09-13 at 10 58 09 AM](https://user-images.githubusercontent.com/85841371/189978878-9b894ce4-ec0d-4c3b-9023-a32d9953d220.png)

**Comment by synapse** [comment]
This should be fixed in [v.1.9.13](https://stacks.rocks/updates/)
