### ISSUE TITLE
Status doesn't show in table view

### ISSUE THREAD

**Issue by bduplanty** [stacks-task-manager/stacks#159]
**Describe the bug**
In the table view, the status does not display.

**To Reproduce**
1. Set a status on a card
2. Go to table view with status column active
3. See no status

**Expected behavior**
System should display status similar to how it displays tags

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version 1.9.12

**Additional context**
N/A

**Comment by synapse** [comment]
This should be fixed in [v.1.9.13](https://stacks.rocks/updates/)
