### ISSUE TITLE
Malicious Activity Found in Stacks-Setup-0.2.8.exe

### ISSUE THREAD

**Issue by theportablegeek** [stacks-task-manager/stacks#16]
**Describe the bug**
Three separate anti-malware sandboxing tools have identified the Windows EXE file as performing malicious activities 🤕 Actual results are linked below:
- [Any.Run](https://any.run/report/6bbd3b3bf069682dd4eab8ab4e340c4cc4100952f4d801f642202dea7dae328f/f1ccbdbc-c5d3-423a-979b-45f76b45429e) 
- [Hybrid Analysis](https://www.hybrid-analysis.com/sample/a07b5f6c9eaf46fddfa16d055d95449c9e23e77c97f63102433e8ca8bf163bd7)
- [Virus Total](https://www.virustotal.com/gui/file/a07b5f6c9eaf46fddfa16d055d95449c9e23e77c97f63102433e8ca8bf163bd7/detection)  

**To Reproduce**
1. Go to any of the above anti-malware identification websites linked above
2. Upload the Stacks-Setup-0.2.8.exe file
3. Wait for Results

**Expected behavior**
Software would not contain malware

**Screenshots**
![image](https://user-images.githubusercontent.com/26526271/82405459-d7e19800-9a18-11ea-92c5-1bcd83c831fa.png)
![image](https://user-images.githubusercontent.com/26526271/82405475-e465f080-9a18-11ea-9e6a-7e0bd6ea0486.png)
![image](https://user-images.githubusercontent.com/26526271/82405510-f9428400-9a18-11ea-8b07-35a61d047a23.png)
![image](https://user-images.githubusercontent.com/26526271/82405527-05c6dc80-9a19-11ea-87a5-f7010aaebe1e.png)
![image](https://user-images.githubusercontent.com/26526271/82405538-0f504480-9a19-11ea-85fc-91c69d350661.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Microsoft Edge
 - Version: 81.0.416.77 (Official build) (64-bit)

**Additional context**
Love the tools and hoping you can shine some light on these issues :)

**Comment by synapse** [comment]
Hi @theportablegeek have you tried this test with any other electron based app?

**Comment by theportablegeek** [comment]
@synapse I have not, but let me do that today and I will post the results 👍

Thanks for quick reply and again, great tool 🙌

**Comment by theportablegeek** [comment]
@synapse here are the results for the DiscordSetup.exe also reported as Malicious

https://www.virustotal.com/gui/file/568177f55700fa4239725ca39ff076fa8ec875f8d02f69c97c39e859861ad168/detection
![image](https://user-images.githubusercontent.com/26526271/82580071-87b32480-9b43-11ea-956e-5bf88960c117.png)

https://any.run/report/6f9ca5577ff3b7cd51e4d2fa099d02e703f626488c5cdfe32c6858be129221be/ef81fb5f-9de5-4ce7-80a3-89f6cf677997
![image](https://user-images.githubusercontent.com/26526271/82580165-a7e2e380-9b43-11ea-8f00-e4d7f3c45875.png)

https://www.hybrid-analysis.com/sample/568177f55700fa4239725ca39ff076fa8ec875f8d02f69c97c39e859861ad168
![image](https://user-images.githubusercontent.com/26526271/82580418-f2646000-9b43-11ea-9139-16199c54b95f.png)
![image](https://user-images.githubusercontent.com/26526271/82580455-f98b6e00-9b43-11ea-9b4c-8a76d799b3d3.png)

**Comment by synapse** [comment]
@theportablegeek this confirms my theory that all electron based apps have the same issue 😉

**Comment by theportablegeek** [comment]
Fair point - I will leave this issue to you to close - but I hear where you are coming from...
