### ISSUE TITLE
Search Not Returning Valid Results

### ISSUE THREAD

**Issue by loikawhaticando** [stacks-task-manager/stacks#160]
**Describe the bug**
I have multiple tasks containing the three-letter string "XOM". Searching for "XOM" returns 0 results when in fact it should return multiple. "XOM" is located in the middle of the title strings for multiple tasks. Rebuilding the search cache doesn't help. The files are saved/synched via Google Drive but I'm only editing them on one machine. Searches for other capitalized three letter terms returns the expected results.

**To Reproduce**
1. Use search box at top of a project, search for "XOM" in a project with multiple tasks who's title contain "XOM"

**Expected behavior**
Search returns the matching tasks. 

**Actual**
Search returns nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/2561017/196543060-59516f6a-1f4d-4e92-96d0-dba0052235a1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 1.9.12

**Comment by mbrock321** [comment]
This appears to be a duplicate report of issue #152 -- Search doesn't work with the letter 'x':

    https://github.com/stacks-task-manager/stacks/issues/152

**Comment by synapse** [comment]
This should be fixed in [v.1.9.13](https://stacks.rocks/updates/)
