### ISSUE TITLE
Import of Stacks 1 workspace not working ... 

### ISSUE THREAD

**Issue by GitSomeSource** [stacks-task-manager/stacks#166]
I can select the source and destination and name the new workspace ... but as I hit the import button ... nuttin'

**Comment by synapse** [comment]
@GitSomeSource should be fixed since Beta 9, but will be improved further in Beta 11 releasing today

**Comment by synapse** [comment]
Closing since this is a Stacks 2 problem. Repo [here](https://github.com/stacks-task-manager/stacks2/issues/)
