### ISSUE TITLE
Stacks 2 Beta Not working

### ISSUE THREAD

**Issue by davidche13** [stacks-task-manager/stacks#167]
I purchased on Appsumo.
I am able download and use stacks 1. This means I can add a license to the software, and choose a folder for a local workspace

Stacks 2 is not functioning properly
- when I try to select a folder for a workplace, I am not allowed. Nothing happens after I select
- also, I cannot add a license to my account. The license spot is grayed out.
- 
Please advise, thanks

**Comment by synapse** [comment]
Hey there @davidche13 please use [this](https://github.com/stacks-task-manager/stacks2/issues) Github repo for reporting Stacks 2 issues.
Stacks 2 while still in beta it might have some issues here and there but overall should be functional. On what OS are you seeing these issues?

**Comment by synapse** [comment]
Closing since this is a Stacks 2 problem. Repo [here](https://github.com/stacks-task-manager/stacks2/issues/)
