### ISSUE TITLE
Stacks 2 will not import from Stacks workspace location ... 

### ISSUE THREAD

**Issue by GitSomeSource** [stacks-task-manager/stacks#168]
Stacks 2 will not import from the original Stacks workspace location ... 

no error message ... and you can click on "Import Workspace" and the button will flash ... and then nuttin'

**Comment by synapse** [comment]
@GitSomeSource this should be recently fixed. have you tried using the latest beta version?

**Comment by synapse** [comment]
Closing since this is a Stacks 2 problem. Repo [here](https://github.com/stacks-task-manager/stacks2/issues/)
