### ISSUE TITLE
stacks 2 won't import stacks 1 workspace - possible cause??

### ISSUE THREAD

**Issue by GitSomeSource** [stacks-task-manager/stacks#169]
I'm running Ventura. stacks 1 shows up in the "files and folders" tab of Privacy and Security but Stacks 2 ... does not. Is that the cause? Does Stacks 2 simply not have access privileges?

**Comment by synapse** [comment]
Hey @GitSomeSource you need to add it to the `Files and Folders` security tab only if the app needs to access a path outside of your users folder, but mostly apps downloaded from the App Store need read write access to files and folders.

**Comment by synapse** [comment]
Closing since this is a Stacks 2 problem. Repo [here](https://github.com/stacks-task-manager/stacks2/issues/)
