### ISSUE TITLE
endless install loop for Stacks 2 ...

### ISSUE THREAD

**Issue by GitSomeSource** [stacks-task-manager/stacks#170]
endless install loop for latest version.

"The currently installed version has either expired or is no longer valid. Please download the new version by clicking the button below."

So ... I do ... same message .. download, rinse, repeat ...

**Comment by synapse** [comment]
Hey @GitSomeSource, just fixed this one. Download the latest beta which is [Beta 12](https://github.com/stacks-task-manager/stacks2/releases/tag/v1.0.0-beta12)
