### ISSUE TITLE
k - Stacks 1 is great ... no global calendar but it works so well

### ISSUE THREAD

**Issue by GitSomeSource** [stacks-task-manager/stacks#171]
k - Stacks 1 is great ... no global calendar but it works so well. I use it and highly recommend it.

Stacks 2 feels like they paid someone on Upwork $20.
At Beta 12 now ... still can't import from Stacks 1.
3 version attempts to resolve that. I'm applying baseball rules here and that's 3 strikes.

I'll use Stacks 1 and will circle back in a few months to see if Stacks 2 works. at. all.
Right now ... it doesn't.

PS - any chance we can get a global cal for Stacks 1?

**Comment by synapse** [comment]
Thank you @GitSomeSource for trying out Stacks 2.
