### ISSUE TITLE
Notes does not hangle http links nicely

### ISSUE THREAD

**Issue by ikrz** [stacks-task-manager/stacks#183]
**Is your feature request related to a problem? Please describe.**
When link is inserted into notes, it is not recognized as a link, you can not click it. If you select inserted link and press insert link buton, opens with empty box.

**Describe the solution you'd like**
Notes should recognized links and provide way to click them.
When link text is selected, clicking add link buton should be prefilled with that link string.

**Comment by synapse** [comment]
Hey @ikrz  this should be fixed since [v2.5.3](https://getstacksapp.com/updates/#version-2.5.3)
