### ISSUE TITLE
Add Custom fields to a card

### ISSUE THREAD

**Issue by RrobertRr** [stacks-task-manager/stacks#19]
**Is your feature request related to a problem? Please describe.**
I wish that I can create own custom fields to a card, as many as I want.
I will also name this custom fields, how I want.

**Describe the solution you'd like**
As a result I wish to have a button for create a custom field.
If I click on this button, there will be created a custom field and I can give this field a name and can fill the field with content, like the description field.
I will create as many custom fields, like I want.
As an example I created a picture:
![custom_field](https://user-images.githubusercontent.com/25011725/83320746-a0f65800-a24a-11ea-91b3-a64dd3008123.png)

**Comment by synapse** [comment]
Hey @RrobertRr check the latest versione 😉
