### ISSUE TITLE
Localization on other language and synchronization with WebDAV

### ISSUE THREAD

**Issue by AlexeyKolodchenko** [stacks-task-manager/stacks#2]
Hi! Tell me please. Do you have at plans on localization application on russian language?

In version application on the Mac i don't find synchronization with the Cloud. I also want synchronization to private WebDAV the server. Thank you for your App.

**Comment by synapse** [comment]
Hi @AlexeyKolodchenko Stacks is being translated to Russian and will be available in the next release 0.2.4.
As for syncing your Stacks library you should move the library path under a Dropbox/Google Drive or any other sync service.
We're working on a server that will do this automatically.

**Comment by AlexeyKolodchenko** [comment]
> Hi @AlexeyKolodchenko Stacks is being translated to Russian and will be available in the next release 0.2.4.
> As for syncing your Stacks library you should move the library path under a Dropbox/Google Drive or any other sync service.
> We're working on a server that will do this automatically.

I have my own web server, and I would like to sync not via google or dropbox, but via webdav Protocol via my server.

**Comment by synapse** [comment]
In that case, for the time being, you should create your own WebDAV microservice.

**Comment by AlexeyKolodchenko** [comment]
> In that case, for the time being, you should create your own WebDAV microservice.

So I have a question, where in the settings to specify the address of my microserver? ))

**Comment by synapse** [comment]
Your microservice, in theory, should read a local path and push your files to your WebDAV server.
IMO you could use something like https://duck.sh/ to sync your local files to your server's
