### ISSUE TITLE
MarkDown preview also in the *description* field

### ISSUE THREAD

**Issue by RrobertRr** [stacks-task-manager/stacks#20]
**Is your feature request related to a problem? Please describe.**
If I'm using markdown syntax in the description, I can't see the interpretation of md.
![md](https://user-images.githubusercontent.com/25011725/83321031-3bf03180-a24d-11ea-9a9e-3034ba3eeed8.PNG)

**Describe the solution you'd like**
I wish to have an edit mode (for example, if I click in the "description" field) and a preview of the md mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by synapse** [comment]
Hey @RrobertRr check version 0.6.0
