### ISSUE TITLE
content by mouse over a item in dashboard view

### ISSUE THREAD

**Issue by RrobertRr** [stacks-task-manager/stacks#21]
If I go over an item on a card in the dashboard view, I want to see the content of this item.
For example (See picture). If I go over the "description" item, I get the information "This task has a description". But I want to see the content of the description (interpreted md).
![mouse_over](https://user-images.githubusercontent.com/25011725/83321200-2e877700-a24e-11ea-9845-e0f62c803942.jpg)

**Comment by synapse** [comment]
Hey @RrobertRr check version 0.2.9
