### ISSUE TITLE
Any plans to make it open source?

### ISSUE THREAD

**Issue by 0lm** [stacks-task-manager/stacks#22]
I looked for an offline, Standalone, non-server Alternative of Wekan for Windows for longer now. And with Stacks, I finally found it. Unfortunately not open source. Are there any plans to make it open source in future?

**Comment by synapse** [comment]
Hey @0lm, not for the moment but we'll open-sourcing the server as soon as we have a stable version.

**Comment by synapse** [comment]
Hi @0lm, check the open-source server available [here](https://github.com/stacks-task-manager/server/tree/develop)
