### ISSUE TITLE
Bug - change the order of checklists and items inside a checklist is not working

### ISSUE THREAD

**Issue by yuriybakalov** [stacks-task-manager/stacks#23]
**Is your feature request related to a problem? Please describe.**
You can not change the order of checklists and items inside a checklist 

**Describe the solution you'd like**
I want to change the order of checklists and items inside a checklist 

**Describe alternatives you've considered**
None

**Additional context**
none

**Comment by synapse** [comment]
Hey @yuriybakalov if you hover over a checklist item (on the very right edge) there should be a menu that enables you to move the item around and also delete it.

**Comment by yuriybakalov** [comment]
Hi @synapse ! Thank you for reply. Yes, I missed the option to change the order of checklist items, but if you have multiple check lists in one task you are not able to change their order. Although the cursor changes to four-directional arrows when you put it on the check list icon. Not sure if there is a possibility to change their order by design.

**Comment by synapse** [comment]
Ah, ok. Yeah that's a feature that will soon be available

**Comment by synapse** [comment]
Hey @yuriybakalov check version 0.2.9
