### ISSUE TITLE
Add folder option to group boards

### ISSUE THREAD

**Issue by dwivedikunal100** [stacks-task-manager/stacks#30]
**Is your feature request related to a problem? Please describe.**
I installed it today,and really liked the UI and features. The only thing is currently it becomes huge list of boards.

**Describe the solution you'd like**
Add folders and collapsable Folder view, so that that boards can be grouped folder wise.

**Comment by synapse** [comment]
Hey @dwivedikunal100, check the latest version 0.10.0

**Comment by dwivedikunal100** [comment]
Thanks looks great!!
