### ISSUE TITLE
Markdown Escaping and Syntax Highlighting/Preformatting

### ISSUE THREAD

**Issue by mkeeler** [stacks-task-manager/stacks#31]
**Describe the bug**
I created a task with the following content: `foo-bar and bar-baz`. Now everything between the two hyphens is formatted with a line through all the text (strikethrough).

I also created a task with an HTTP path in it such as `v1/foo/bar`. This ends up getting italicized.

Lastly when I enclose anything in backticks it doesn't show up as monospaced "code".

For the first two items it would be great if there was a way to escape the markdown characters. For the second it would just be nice if the markdown rendering supported code formatting as this would be another way of preventing characters such as a hyphen or slash from getting markdown formatted. I know I can turn off markdown conversion in general but I am actively using it in other cases.

I could gather some screenshots if need be but I think this should be fairly simple to reproduce.

**Comment by synapse** [comment]
Hey, @mkeeler thanks for the feedback. This will be fixed in the next release but unfortunately, the syntax will slightly be changed

**Comment by synapse** [comment]
Hey @mkeeler check version 0.6.0 although take a look at the slightly changed markdown syntax
