### ISSUE TITLE
Resizing the task edit window

### ISSUE THREAD

**Issue by kernelplv** [stacks-task-manager/stacks#32]
Hi! The window for editing the task is rather small in relation to the total diagonal of the maximized application window.

![](https://i.imgur.com/PUXaq3g.png)

Thank you!

**Comment by synapse** [comment]
Hey @kernelplv there's a new option in the Preferences in version 0.5.1 that makes the task detail window larger.

**Comment by kernelplv** [comment]
> Hey @kernelplv there's a new option in the Preferences in version 0.5.1 that makes the task detail window larger.

Exactly what I wanted!
