### ISSUE TITLE
Problems with drag n drop

### ISSUE THREAD

**Issue by kernelplv** [stacks-task-manager/stacks#33]
**Describe the bug**
Drag n drop does not work correctly. See gif

**Screenshots**
![](https://i.imgur.com/V6HMfrH.gif)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 0.4.0

Thank you!

**Comment by synapse** [comment]
Hey @kernelplv can you send me your board via email if there's nothing sensitive in there? I would like to test it out using the Cyrillic letters

**Comment by kernelplv** [comment]
> Hey @kernelplv can you send me your board via email if there's nothing sensitive in there? I would like to test it out using the Cyrillic letters

Done!

**Comment by synapse** [comment]
@kernelplv I've been playing with your board and I cannot recreate the problems from your video.
Are there some specific steps you did to make the drag act strange?

**Comment by kernelplv** [comment]
> @kernelplv I've been playing with your board and I cannot recreate the problems from your video.
> Are there some specific steps you did to make the drag act strange?

Oh, if I knew .. Maybe there were some errors on the board with the upgrade? This board exists from the moment when the Stacks repository was 15 days :)

**Comment by synapse** [comment]
Hmm strange, the board structure was not changed until now.
I'll let this issue open. Keep me in touch if you encounter the same issue in the new board.

**Comment by synapse** [comment]
Version 0.5.0 is imminent. Please check with that also. If still persists please resend me the board at info@stacks.rocks and telling me exactly which task from what column should I move in order to recreate the issue.

**Comment by kernelplv** [comment]
> Version 0.5.0 is imminent. Please check with that also. If still persists please resend me the board at [info@stacks.rocks](mailto:info@stacks.rocks) and telling me exactly which task from what column should I move in order to recreate the issue.

Done! I recorded a video and added it to an attachment

**Comment by synapse** [comment]
Hey @kernelplv check version 0.6.0

**Comment by kernelplv** [comment]
Yes, the problem was solved, thanks!
