### ISSUE TITLE
Remove Horizontal Scroll Bar

### ISSUE THREAD

**Issue by Aamir2000** [stacks-task-manager/stacks#35]
# Remove Annoying Horizontal Scrollbars
Hello, I'd like to have some sort of custom scrollbar or no scrollbar at all with these boards because that scrollbar at the bottom is very obnoxious and very distracting when using dark theme because its white colored it'll help in reducing that distraction if those scrollbars are invisible or custom black colored. 

**Describe the solution you'd like**
I'd want either black colored scrollbar or rather no scrollbar will be amazing

**Describe alternatives you've considered**
No scrollbar is the best solution for me you can give a option to hide those because I'd guess a grandma wouldn't be able to figure out how to scroll without scrollbar isn't it so I guess

**Additional context**
Just remove those scrollbars Horizontal / Vertical both

**Comment by synapse** [comment]
Hey @Aamir2000, I presume you're on Windows? 😅

**Comment by Aamir2000** [comment]
Isn't it too obvious 😂

**Comment by synapse** [comment]
Hi @Aamir2000 check version 0.6.2

**Comment by Aamir2000** [comment]
Man I love it 💕💕 it looks awesome now I don't mind not having those ugly looking windows scrollbars you really save my life after using Trello my experience was like 🤢 so I wanted something more elegant looking and I've been using this thing struggling with this scrollbar issue for always 2 yrs now but thank god its fixed now I'm super happy bruh thanks
