### ISSUE TITLE
easy collapse/expand

### ISSUE THREAD

**Issue by greatoe** [stacks-task-manager/stacks#36]
Hi Stacks team,

Is it possible to add features to let user ( me :-) ) easily collapse and expand a stack?

Say a quick button (instead of first click the ... then click 'collapse') or a keyboard shortcut to collapse a single stack, and then click anywhere on the whole collapsed stack bar (instead of a button at the bottom of the bar) to expand it?

I have quite a lot of stacks on a single board that I can view all my information simultaneously.  But without collapsing I can only view a few of them.

Thank you,

Zhou

**Comment by synapse** [comment]
Hey @greatoe check version 0.6.0
