### ISSUE TITLE
Description & Tasks In Card View

### ISSUE THREAD

**Issue by Aamir2000** [stacks-task-manager/stacks#39]
**Is your feature request related to a problem? Please describe.**
I know this is probably too much for one guy to complaint about something but I like this software and not only I wanna make it more useful for myself I wanna see it grow too. So this brings me to my actual issue which is that description and tasks we add inside our tasks ( no pun intended ).

**Describe the solution you'd like**
I think it should show that description and tasks inside of that task card basically so we don't have to click on task, open it to see what description we have set for that task and what tasks we have to finish for that card. ( basically make it so we don't have to open that giant model to see our description and tasks ) otherwise for accessing and adding due dates and other things its fine.

**Describe alternatives you've considered**
Now I think showing all tasks is not possible considering limited work area for smaller screen sizes I think what you could do instead of adding all the tasks to the card itself you can make a popup that shows up after clicking on that small checklist icon that tells the user that some tasks are assigned for this card. So basically make it so that popup opens on single click instead of double clicking it ( for lazy people ) and it should just contain our tasks ( all tasks ( tasks = todo list, checkbox list whatever you call it ) ).  

**Additional context**
I think its pretty straightforward as in what I was trying to say but I know it gets messed up as we start implementing stuff to a big codebase so best of luck I guess ( These are just somethings I'd love to have ) no burden on you man I really appreciate that you even took time to fix that scroll bar issue I had before. It was awesome

**Comment by synapse** [comment]
Hey @Aamir2000 please check the the new `eye` toggle button that enables the description in the card and the new popups from the card footer

**Comment by Aamir2000** [comment]
Wow this is awesome It's like past midnight here but I still woke up to check out this update just because I know man you've done some significant work on this app and I love it thanks for fixing these issues of mine. I appreciate your efforts a lot.....I'm not gonna bother you again with some stupid request I think I'm pretty satisfied unless you want me to point out things that can be good to have in this app. Again thank you sooooooo much ❤️❤️❤️ much love

**Comment by synapse** [comment]
Sure @Aamir2000 every feedback is good, so keep them coming!
