### ISSUE TITLE
Open link in browser instead in stacks app

### ISSUE THREAD

**Issue by lakuapik** [stacks-task-manager/stacks#41]
**Is your feature request related to a problem? Please describe.**
When we open link in stacks app, it opened in same window as stacks. 

**Describe the solution you'd like**
Would be nice if the link opened in the browser instead of the stacks app. So we still have same session as the browser when visiting the link.

**Describe alternatives you've considered**
Maybe add some configuration to choose the link opener.

**Additional context**
screenshot:
![Peek 2020-09-16 15-05](https://user-images.githubusercontent.com/20186786/93309767-17d15400-f82e-11ea-8d9d-17d332312d64.gif)

thanks a lot!

**Comment by synapse** [comment]
Hey @lakuapik, this is a bug since it should have opened in the default browser. Thanks for the feedback

**Comment by synapse** [comment]
@lakuapik Fixed in v0.6.3
