### ISSUE TITLE
Stacks colors & Swimlanes

### ISSUE THREAD

**Issue by fredserva** [stacks-task-manager/stacks#43]
Hi!
it would be great if it was possible to attach a color to a stack and to add swimlanes to a board.

Thanks!

**Comment by synapse** [comment]
Hey @fredserva by swimlanes do you mean something like an automation? Because if not you could just reorder the stacks to match your process

**Comment by fredserva** [comment]
No, I mean horizontal categorization.
eg:
[Defects/Bugs & Features in this example](https://kanbanize.com/wp-content/uploads/website-images/kanban-resources/software_kanban_board.png)

**Comment by synapse** [comment]
hey @fredserva, we've added a new Stack color/tint option in the latest v 0.9.0.
As for the swimlanes, we won't support it for the time being.
Closing this issue
