### ISSUE TITLE
App going white after moving tasks

### ISSUE THREAD

**Issue by Bluetexon** [stacks-task-manager/stacks#44]
**Describe the bug**
Moved all tasks from the demo board to the right. The app went white and even after a restart it stays white.

**To Reproduce**
1. Opened Stacks
2. Drag and Dropped all Tasks on the demo board from the first column to the second one

**Expected behavior**
The app not going white and continue to function.

**Screenshots**
I've opened the DevTools and saw this. I guess this is causing the Problem
![image](https://user-images.githubusercontent.com/22718113/93926568-f5e93d00-fd17-11ea-9dec-2f9d8dc5d289.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium (Electron App)
 - Version 0.7.0

**Comment by Bluetexon** [comment]
I could also send you the corrupted welcome.board file. In case you would like to have a look in there

**Comment by synapse** [comment]
Hey @Bluetexon, thanks for the feedback.
Since I cannot reproduce the error, can you please remove the demo board and let Stacks recreate it at the next lunch?
Can you check if still crashes? I also saw that you're from Germany which means that is installing a demo board in german?  Could you maybe try with the English version attached?


[welcome.board.zip](https://github.com/stacks-task-manager/stacks/files/5263561/welcome.board.zip)

**Comment by Bluetexon** [comment]
Hello,
thank you for the fast response.
I tested it a bit more, used your english board file and it seems to be happening _sometimes_ when moving the red, important task. Not every time, but sometimes. Sadly I can't seem to find a specific scheme. I was playing around with it, which is why I moved them a bit too quickly, but I thought it is still worth reporting :)
I made a small gif which can hopefully help you a bit.
[https://i.imgur.com/Q4Yhbdk.gif](url)

**Comment by Bluetexon** [comment]
I did a bit more digging and found the line which is causing these issues.
![image](https://user-images.githubusercontent.com/22718113/93929760-a0fbf580-fd1c-11ea-9adc-29386eed9993.png)
Stacks can start as usual and load the board correctly when I remove this line.

**Comment by synapse** [comment]
After seeing your Gif I was able to recreate the error in my dev environment. Thanks for the help. In the meantime go slow 😅

**Comment by Bluetexon** [comment]
I will 😉
Thank you for your help and thank you for making this app. I really like it 😀
