### ISSUE TITLE
Option to show checklist in Kanban View

### ISSUE THREAD

**Issue by RrobertRr** [stacks-task-manager/stacks#46]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I first musst klick on a ticket, to see the Checklist.

**Describe the solution you'd like**
I wish to see the Checklist of a Task in the Kanban Overview.
Here is an example, how I wish it:
![image](https://user-images.githubusercontent.com/25011725/94672700-ea000b00-0315-11eb-8169-3b8f15f3d70d.png)

**Comment by synapse** [comment]
Hey @RrobertRr check the latest version 0.8.0
