### ISSUE TITLE
Color coding text in tasks

### ISSUE THREAD

**Issue by RaidanAlyssi** [stacks-task-manager/stacks#48]
It'd be great if we could color code text in tasks. I've been using bold + italics to make text standout but it'd be nice to be able to change colors of words so that certain words would stand out more uniquely.

For example something like this: https://www.bbcode.org/examples/?id=6

**Comment by synapse** [comment]
Hey @RaidanAlyssi, nice idea. In the meantime, you could use the `highlight` syntax (`::word::`) to emphasize your words

**Comment by synapse** [comment]
Hey @RaidanAlyssi check version 0.8.0
