### ISSUE TITLE
[Enhancement] Search in all boards and not only in the active one

### ISSUE THREAD

**Issue by pidgeon777** [stacks-task-manager/stacks#49]
Actually, search only occurs on the active board. It would be cool to add an option so that search can be performed on all available boards, eventually by adding some text to the reported search results specifying the board on which the task has been found.

Or better, display the found task in split sections in the search results page, one for each board in which the task has been found. For example, the search results page could be presented this way:

Board X
_____________

Task X
Task Y

Board Y
_____________

Task Z

**Comment by synapse** [comment]
Hey, @pidgeon777 this most likely to be done only with the online version using the [server](https://github.com/stacks-task-manager/server). The current standalone/offline version is kinda hard since the boards are not all loaded into memory. Only the current board is loaded.

**Comment by pidgeon777** [comment]
Thanks for the prompt reply. What a pity... hopefully in the future it will be possible to do that even for the offline version. It would be quite a useful and time saver feature, already implemented in similar tools. Especially when dealing with a big number of available boards.

**Comment by pidgeon777** [comment]
I would add, even more useful when searching for tags, for example, #Urgent. The current implementation would require to select each board and search for the #Urgent tag... by making this tag system almost useless, I think (one would expect tags to be common to all boards thus searchable). Just my opinion, though.

**Comment by synapse** [comment]
Hey @pidgeon777  check out the latest version that was just released 😉
