### ISSUE TITLE
[Feature] Button/command to refresh the board

### ISSUE THREAD

**Issue by pidgeon777** [stacks-task-manager/stacks#53]
It is possible to edit the JSON file of a board while running stacks. A refresh button could be added (F5 shortcut) to refresh the modified board currently displayed in stacks.

**Comment by pidgeon777** [comment]
Or, even better, add an option to automatically refresh the displayed board when the library files are externally modified.

**Comment by synapse** [comment]
Hey @pidgeon777 to refresh a board try using `Ctrl + R` on Windows and Linux or `Cmd + R` on Mac.
As for the options in the screenshot, there were intentionally removed due to some bugs but will be restored ASAP.

**Comment by pidgeon777** [comment]
Automatic reload based on external file modification would be nice, indeed. Thanks for the tip!

**Comment by synapse** [comment]
hey @pidgeon777, check the new menu item for refreshing the board in ver. 0.9.0

**Comment by pidgeon777** [comment]
Will do! Thanks for the enhancement.

Now I'm just hoping this feature will be one day be implemented, it's the only thing holding me and some fellows from migrating from Trello to stacks:

https://github.com/stacks-task-manager/stacks/issues/49

**Comment by synapse** [comment]
Hey @pidgeon777, in version 0.9.3 also added automatically reload in case the library changed

**Comment by pidgeon777** [comment]
This is a great feature, thank you!

**Comment by pidgeon777** [comment]
I think your project has a lot of potentials but it needs more visibility somehow.

**Comment by synapse** [comment]
You're right but you also have to consider the fact that Trello has a big corporation behind it with a lot of budget 😅 
We'll get there 👍

**Comment by pidgeon777** [comment]
Understandable, but potentially many developers might be interested in contributing free of charge to the development of this project, for example through pull requests or bug reports. In this way, ideas may emerge that allow you to quickly and effectively implement the most complicated features required.
However, it is certain that the project should be publicized as much as possible for this to happen, for example by reporting it to industry blogs (reviews of open source tools and freeware, etc.).
