### ISSUE TITLE
clarify relation to  Stacks 1.4.3 from the Mac App Store

### ISSUE THREAD

**Issue by core-code** [stacks-task-manager/stacks#54]
can you please clarify what relation this app has to the 'Stacks' that was distributed on the Mac App Store a while back?

is it a new generation of the same app? if so, why does it have a lower version number?

is it a completely different app? if so, why does it have the very same bundle-identifier which may only be identical for identical apps?

thanks for clearing this up!

**Comment by synapse** [comment]
Hey @core-code, why do you need this?

**Comment by core-code** [comment]
if there are two apps from the same vendor with the exact same name this creates confusion. clarifying whether this is a successor app or supposed to be something different would help clear up the confusion. 

since you don't see the need explain this, lets close this issue.
