### ISSUE TITLE
Checklist tooltip message on eye icon is flashing at stacks column when zero or 1 item is active

### ISSUE THREAD

**Issue by vilagszottes** [stacks-task-manager/stacks#55]
**Describe the bug**
Checklist tooltip message (Show completed tasks / Hide completed subtasks) on eye icon is flashing fast at stacks column when zero or 1 item is active.

**To Reproduce**
1. If the task is not has checklist, at edit dialog's bottom area click on "Add a checklist" icon to add 1 or more item.
2. After exit from editing, on stack column at the task's bottom left corner when clicking on the checklist icon with the forefinger mouse pointer, the checklist appears with popup effect.
3. When checking the items and all is checked, after I click the eye icon left next to checklist title - Hide completed subtasks - and after it was hidden, I move again the mouse pointer above the eye icon, and then the icon tooltip message is flashing fast. Same flashing effect when "hide" is clicked and only one item is in unchecked state. Same bug when the checklist has only one item and I move the mouse pointer above the eye icon, both hide or show state, the tooltip message is flashing.

**Desktop:**
 - OS: Windows 8.1 64bit
 - Stacks version: 0.8.3 (Windows x64 portable)

**Comment by synapse** [comment]
Ok, found it

![](https://i.imgur.com/n6mMcYP.gif)

@vilagszottes thanks for the feedback

**Comment by synapse** [comment]
Hey @vilagszottes, this also will be fixed with the latest release later today 0.8.4.
