### ISSUE TITLE
Stack title's name change is not saved in version 0.8.3

### ISSUE THREAD

**Issue by vilagszottes** [stacks-task-manager/stacks#56]
Hello again!

I've found another bug: stack column title's name change is not saved in versions: 0.8.2 and 0.8.3.
But in earlier version 0.8.0 it works well, the title is saved ok.

Anyway, I recently started using the program to manage work tasks. I really like it.
I've added my list at AlternativeTo: https://alternativeto.net/list/18398/notetaking-calendar-to-do-list-apps/
I'll promote it on my personal link collection website if it will restart in the next months.

Thanks a lot for your work.
Have a nice day.
Jefferson
Project Vilagszottes / Jo Zene. Good Music

**Comment by synapse** [comment]
Hey, @vilagszottes will be fixed in the next release 0.8.4 later today. 
Thanks for your feedback and the promotion
