### ISSUE TITLE
Right click on collapse stack

### ISSUE THREAD

**Issue by farouqzakwan** [stacks-task-manager/stacks#57]
**Right click on collapse stack**
User Interface for renaming stack have problems when collapsing stack and right click it on it. 

**To Reproduce**
1. Collapse Stack
2. Right Click on stack (User Interface have problems)
3. Open Stack from Collapse
4. Rename the stack title (User Interface have problems)

![1](https://user-images.githubusercontent.com/7401765/96693517-ebbf6a80-13b9-11eb-93a9-caf82ac91a1e.PNG)
![2](https://user-images.githubusercontent.com/7401765/96693522-ed892e00-13b9-11eb-80a3-b965288ac873.png)
![3](https://user-images.githubusercontent.com/7401765/96693525-ed892e00-13b9-11eb-828b-29445b16ebff.png)

**Comment by synapse** [comment]
Hey @farouqzakwan, this should be fixed in the latest release 0.8.5
