### ISSUE TITLE
Problem while loading the board

### ISSUE THREAD

**Issue by ranjithkumark8** [stacks-task-manager/stacks#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux]
 - Version [e.g. 0.2.x]

**Additional context**

**Comment by ranjithkumark8** [comment]
Os- windows -10 latest version
When I was trying to create bard after installing. I can't able to load the board for your reference I'm attaching a screenshot 
![image](https://user-images.githubusercontent.com/57569434/98465479-498fe700-21ef-11eb-9341-1273934243ce.png)

**Comment by synapse** [comment]
Hey @ranjithkumark8, could you check on the newest version 0.9.5. Let me know if you're still having issues
