### ISSUE TITLE
Getting this error on first launch 

### ISSUE THREAD

**Issue by realJema** [stacks-task-manager/stacks#61]
I am getting this error when I first launch the app. 
My computer specs
Win 10
I7
64bit 
![image](https://user-images.githubusercontent.com/16238730/98534936-8c9c9980-2285-11eb-8142-bf9b69fa930c.png)

**Comment by synapse** [comment]
Hey @realJema, could you check out the newly released version 0.9.5? The problem you've mentioned should be fixed.

**Comment by realJema** [comment]
it was resolved thanks
