### ISSUE TITLE
Auto scroll when dragging a task to most left/right

### ISSUE THREAD

**Issue by jokysatria** [stacks-task-manager/stacks#63]
**Is your feature request related to a problem? Please describe.**
Currently, when dragging a task out to most left/right, the window won't scroll. This makes it difficult to move a task to another stack that is on another side.

**Describe the solution you'd like**
The window will automatically scroll as like as when dragging a stack.

**Describe alternatives you've considered**
Actually I can scroll the window manually + drag my task, but there's a bug that I can't drop my task: it back to previous position.
![Stack Drop Bug](https://user-images.githubusercontent.com/69371378/100871812-732ced00-34d3-11eb-84b3-e3f71bfc46f0.gif)
 
**Additional context**
![Stack Request](https://user-images.githubusercontent.com/69371378/100865904-838c9a00-34ca-11eb-85ec-442ce498ec0b.gif)

**Comment by synapse** [comment]
Hey, @jokysatria in the next version this should be fixed 😉 . Thanks for the feedback

**Comment by synapse** [comment]
Hey @jokysatria, should be fixed in 0.10.1 even though I had to disable the fixed height stacks option for the time being - the drag-and-drop library has some issues with nested scroll elements 😢
