### ISSUE TITLE
Tint not work or unclear how to use

### ISSUE THREAD

**Issue by kberkut** [stacks-task-manager/stacks#65]
**Describe the bug**
Tint not work or unclear how to use

**To Reproduce**
1. Go to 'settings of board'
2. Click on 'Tint'
3. See empty

**Expected behavior**
View menu with different colour

**Desktop (please complete the following information):**
 - OS: [Arch Linux x86_64 -> 5.9.13-arch1-1 + i3wm]
 - Version Stack-Linux-0.11.0-beta.1.AppImage  or Stack-Linux-0.10.1.AppImage

![изображение](https://user-images.githubusercontent.com/57869227/102445562-cf981c80-403c-11eb-915c-c84894a85f7d.png)

**Comment by synapse** [comment]
Hey, @kberkut I think you've downloaded the Beta version instead of the stable latest version which is [10.0.1](https://github.com/stacks-task-manager/stacks/releases/tag/v0.10.1).
Make sure you delete the current Stacks library by the beta version - should be found in your `Documents` folder

**Comment by kberkut** [comment]
> Hey, @kberkut I think you've downloaded the Beta version instead of the stable latest version which is [10.0.1](https://github.com/stacks-task-manager/stacks/releases/tag/v0.10.1).
> Make sure you delete the current Stacks library by the beta version - should be found in your `Documents` folder

Thanks. Beta version not have tags.
![изображение](https://user-images.githubusercontent.com/57869227/102487949-620be080-407c-11eb-9eed-899c55f0ef90.png)

**Comment by synapse** [comment]
Yes, at the moment the Beta does not have the tags since I'm working on having a new Board Preferences window.

**Comment by kberkut** [comment]
Thank you.
I think may be colour may be set more visible for task and columns. For example:
![image](https://user-images.githubusercontent.com/57869227/102582245-3e47a980-4113-11eb-8fcb-5aad21a2665d.png)

**Comment by synapse** [comment]
> Thank you.
> I think may be colour may be set more visible for task and columns. For example:
> ![image](https://user-images.githubusercontent.com/57869227/102582245-3e47a980-4113-11eb-8fcb-5aad21a2665d.png)
> If column is very long that may be:
> ![image](https://user-images.githubusercontent.com/57869227/102583084-0477a280-4115-11eb-8a2f-086718488c4d.png)

This feature is already available on the List View in the Beta version. I'll add it also to the Board View as a togglable option of the board

**Comment by synapse** [comment]
Hey @kberkut a quick screenshot from the latest Beta version (not yet released)

![](https://i.imgur.com/In503E0.png)

![](https://i.imgur.com/U5rVvoL.png)

**Comment by kberkut** [comment]
That's better. Thank you.

**Comment by synapse** [comment]
Hey @kberkut check out the latest version that was just released 😉
