### ISSUE TITLE
The moving of tasks

### ISSUE THREAD

**Issue by kberkut** [stacks-task-manager/stacks#66]
Can you do menu for move of task?
Folder -> Board -> Column
And important: options will be not remove (tags, date and etc.)

**Comment by codegarden13** [comment]
I can drag a task to another project. **If drag is possible, drop should also be possible** because drag makes the user feel drop should work. If it does not, it makes him/her believe it is a bug ...  He will loose a bit of trust in the product.

**Comment by synapse** [comment]
Hey, @kberkut @codegarden13 there's a new Copy/Move wizard available now in version 1.3.0
