### ISSUE TITLE
Where is TAGS ?

### ISSUE THREAD

**Issue by pwndumb** [stacks-task-manager/stacks#69]
**Is your feature request related to a problem? Please describe.**
I love the app but I really not found in easy way to tag my tasks.

![Tags-1](https://user-images.githubusercontent.com/6491534/104600066-484bc200-5657-11eb-9cec-4ff7c2382da9.png)

When I click in this button nothing happens. I run in mac and windows. The result is the same. The possibility can tag tasks is awesome, but is not came with a little usability.

**Comment by synapse** [comment]
Hey @pwndumb, we are aware of this issue and we're already done big improvements that will be available in the next major release. 
Until then to manage your tags - just open the Preferences side panel and you should be able to add or edit them under the board section.
