### ISSUE TITLE
Inconsistent behaviour of tags checkmarks in context menu

### ISSUE THREAD

**Issue by sandlex** [stacks-task-manager/stacks#70]
**Describe the bug**
When assigning a tags to a task the state of the checkboxes in context menu is not reflecting assigned tags correctly until menu is not closed.

**Screenshots**
https://user-images.githubusercontent.com/841632/106209681-bbac1280-61c5-11eb-9b12-bd84f7aa1089.mov

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Version: 0.10.2 (0.10.2)

**Comment by synapse** [comment]
Hey @sandlex, please check version 1.0.0 that was just released. Should have a better tags picker and manager 😉

**Comment by synapse** [comment]
This issue should be fixed with version 1.3.0
