### ISSUE TITLE
all my data is erased after update 

### ISSUE THREAD

**Issue by dsgrishin** [stacks-task-manager/stacks#76]
Today 04/21/2021 the program has been updated. Version 1.1.3. After the update, all my boards, tasks and other data rolled back to the level of a year ago. It was possible to restore the data only thanks to a backup from the cloud. But in the new version there is no cloud backup option.
I am very upset that the program does not provide data safety! 

**Expected behavior**

**Screenshots**
I expected that after the update, all my data would remain in place. 

**Desktop (please complete the following information):**
 - Desktop version
- Windows 10 OS

**Comment by synapse** [comment]
Hey @dsgrishin, version 1.1.x introduced workspaces. Is it may be that your old library path was not the default one? 
If yes then just add a new Workspace and point it to the old folder where your library previously was.
Let me know if this solved your issue

**Comment by doctopus** [comment]
Same problem here. After 1.1.4 update, all old tasks are gone. Now showing the welcome screen with default tasks. Where do I find my old folder. The Documents/Stacks folder was created by this update.

**Comment by synapse** [comment]
Hey guys @doctopus @dsgrishin,
There is literally no algorithm for deleting a library. As a result, it's possible that the software reinitialized the demo file in a separate folder to where it originally ran.

There are two options available to you.
1. do a global search in the OS and look for a `structure.tree` or `*.project` file
2. open the current workspace folder and check inside if there are more `.project` files inside of it

Please keep me updated on your findings.

**Comment by dsgrishin** [comment]
@synapse Apparently, the problem is precisely the appearance of spaces and the not very successful update algorithm.

**Comment by synapse** [comment]
@dsgrishin can you elaborate? To know what to fix, I need to know exactly what happened.

**Comment by dsgrishin** [comment]
@synapse Hey!
About a year ago I installed your program for the first time and started using it.
After a while, I found out that you can synchronize it with the cloud and store the data there, which I did.
Recently, I updated the version and in the documents / stacks directory, which was opened by an automatically created new space, I saw only tasks that were one year old, i.e. everything I filled in during the year was gone.
When I realized that it was impossible to synchronize the new version with the cloud and retrieve data from the cloud, I copied the above folder from the cloud to my computer and all tasks appeared again.

I suspect that after I set up to work with the cloud a year ago, the program stopped writing data to the local directory and after the update, it showed me what is in the local version and has not been updated for a year.

**Comment by synapse** [comment]
So in other words the app changed back to its default folder and didn't consider your cloud-based folder?

**Comment by dsgrishin** [comment]
If the previous version of the program did not work with the local folder if the cloud is connected, then yes, this is the only logical option.

**Comment by synapse** [comment]
Yes, it reverted back to the folder in your Documents instead of using your Cloud synced folder

**Comment by doctopus** [comment]
@synapse I wanted to report back that I could search the structure.tree containing folder and add a new workspace pointing to that folder, now all my data is visible under the new workspace. Problem solved. If the new update could have preserved the previous workspace while adding the new welcome workspace, it would have been nice. But glad to have found the solution. Thank you.
