### ISSUE TITLE
Max 3 projects limit bypass

### ISSUE THREAD

**Issue by ualvesdias** [stacks-task-manager/stacks#78]
**Describe the bug**
It's possible to bypass the limit of 3 projects on free versions of the app by simply duplicating an existing project and renaming it.

**To Reproduce**
1. Right click on any existing project, chose Duplicate Project
2. Choose a new name for the duplicated project
3. Move the new project into another folder, if desired
4. Change the contents of the new project, if desired

**Expected behavior**
By trying to duplicate an existing project on the free version of the app when there are already 3 projects created (the max limit), there should be the same message saying that the limit was reached.

**Screenshots**
![image](https://user-images.githubusercontent.com/11967258/117301443-08505b00-ae51-11eb-9747-a32ec5d34954.png)
![image](https://user-images.githubusercontent.com/11967258/117301550-1f8f4880-ae51-11eb-9add-6797d9315024.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.1.4

**Additional context**
I know that I'll probably loose my projects, but I'd rather be helping you guys out because this is an amazing app.

**Comment by synapse** [comment]
Hey @ualvesdias, thanks for finding the security flaw 😅 . Please get in contact with me, I have something for you 😉

**Comment by ualvesdias** [comment]
Thanks! I've sent you an email at thesynapseproject@gmail.com.

**Comment by ualvesdias** [comment]
> Hey @ualvesdias, thanks for finding the security flaw 😅 . Please get in contact with me, I have something for you 😉

Thanks! I've sent you an email at thesynapseproject@gmail.com.
