### ISSUE TITLE
Stacks keep crashing at startup

### ISSUE THREAD

**Issue by pidgeon777** [stacks-task-manager/stacks#86]
**Describe the bug**

As soon as stacks starts, it crashes.

**To Reproduce**

Simply open stacks.

**Expected behavior**

It should not crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/13739892/127740881-ccfa3282-b2b1-46e3-a045-d030f78659e7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Pro

**Additional context**

Also, when it crashes it is not possible to click on any of its buttons (*Send report*, *Relaunch Stacks*...).

Stacks version is *1.4.0* (it didn't crash with the previous version).

I was tempted to buy a Pro license, but given this issue unfortunately I don't think it would be possible for me to proceed in doing so.

**Comment by synapse** [comment]
I apologize for the inconvenience. There were some conflicts with some very old project files.  Should be fixed with the latest version 1.4.1

**Comment by synapse** [comment]
@pidgeon777 can you tell me if it's working for you with the latest version?

**Comment by pidgeon777** [comment]
I can confirm that with the new 1.4.1 installer it now works.

**Comment by pidgeon777** [comment]
Are you open to new suggestions, improvements, ideas, to be implemented in your tool?

If yes, may I report them on this GitHub repository?

**Comment by synapse** [comment]
Of course @pidgeon777, you could also join our Slack channel and contact me directly

**Comment by pidgeon777** [comment]
Ok. I just bought a Pro license.

Keep up the great work, e in bocca al lupo 👍.

**Comment by synapse** [comment]
Grazie @pidgeon777 ☺️
