### ISSUE TITLE
space bar toggles task done/todo but also scrolls window down

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#88]
**Describe the bug**
When using the space-bar to toggle a task between done/to-do, the board view window also pages down to show more tasks, if some stack has more tasks than can fit in the window. (Sometimes this hides the task I've just toggled, if it's near the top of the window.)

**To Reproduce**
Make sure your project has a stack with more tasks than can fit in the window vertically. 
Preferences/Projects/Click to Select Tasks or Stacks -- checked
In Board View, select any task 
hit spacebar 
   todo/done state of task will toggle
   window will page down to reveal more tasks that were hidden at the bottom

**Expected behavior**
todo/done task should toggle, but the window should not scroll down.

**Desktop (please complete the following information):**
OS: OSX 10.14.6, Mojave
Stacks Version 1.3.5

**Comment by synapse** [comment]
@mbrock321 should be fixed in 1.4.5

**Comment by mbrock321** [comment]
Thanks -- that was quick!
