### ISSUE TITLE
Projectnames invisible and people-lists not available 

### ISSUE THREAD

**Issue by JohnAJansen** [stacks-task-manager/stacks#92]
Dear support,

We are using Stacks for a few weeks now, but encountered an issue (after de last update, version 1.5.0.....?). See screenshot below - the names of the projects is invisible, and the people-lists are gone. I do not know whether this is a general issue with the new version, or specific for us, but I wanted to let you know.

![Issue Stacks](https://user-images.githubusercontent.com/65544470/135624931-5882a037-e802-4f3c-b291-6892010119d8.png)

We appreciate your help, and hopefully you can solve the issue.

Thank you!
Regards, John

**Comment by synapse** [comment]
Hey, @JohnAJansen could you jump into a quick chat via our website or even better our Slack channel?
