### ISSUE TITLE
Intermittent bug - unable to click on Month dropdown when setting Dates

### ISSUE THREAD

**Issue by ElMuggs** [stacks-task-manager/stacks#94]
**Describe the bug**
When setting dates the 'month' dropdown intermittently fails to recognize the mouse - it's about a 50/50 to 30/70 in frequency.  
Hovering over shows the mouse pointer vs click option. This is resolved by clicking 'all day' at the bottom of the window at which point the month dropdown works as expected. - it can also sometimes be fixed by selecting a date or the year first. 

**To Reproduce**
1. Double click a date field
2. Try to click on the 'Month' to change it
3. Sometimes it works, sometimes it doesn't.
4. If it fails to work tick 'all day'
5. this will then allow you to change the month

**Expected behavior**
Clicking the month dropdown should expand the selection menu. 

**Screenshots**

![buggy dates](https://user-images.githubusercontent.com/92188600/136718707-3419e695-567e-48c5-b620-ccccdd6bcaa5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 1.5.0 - 1.5.2 

**Additional context**
Happens in 1.5.0 and future releases - and in both free/professional version. 
Ideally would also be good to be able to write in dates vs having to manually set it each time in order to speed up data entry/increase accuracy - you could use the universal ISO date format of YYYY-MM-DD below 'two weeks from now' and later add a US/EU date format option if you want to be fancy. ;)

**Comment by synapse** [comment]
@ElMuggs this issue should be fixed using the latest version, can you confirm?

**Comment by ElMuggs** [comment]
Thank you, I haven't had a chance to confirm as it was only ever
intermittant but it looks good so far! -  I'll repost if the bug occurs
again

Thank you :)
