### ISSUE TITLE
Automation for repeating tasks within Stack

### ISSUE THREAD

**Issue by chriscatalino** [stacks-task-manager/stacks#95]
**Is your feature request related to a problem? Please describe.**
For project tasks that need to be done weekly, monthly, etc., it would be helpful to automatically create the task X days/hours before it is due. 

**Describe the solution you'd like**
Multiple implementation can be envisioned:
1. Create task, mark as repeating with X occurrence interval, set time prior to due date for task to be created. This would be a new task every time
OR.
2. Create task, mark as repeating with X occurrence interval, keep task as completed in stack until the occurrence interval is hit,  update due date/completion status. Deleting the completed task in between repeats would delete the task permanently and it would not be repeated. 

**Describe alternatives you've considered**
Trello offers this as one of the built in "power-ups" as does TickTick

**Additional context**
None.

**Comment by synapse** [comment]
Hey @chriscatalino this feature will be available in the next version 1.6. You can already check it out in the 1.6.0 beta 1 and leave a feedback in our Slack channel

**Comment by chriscatalino** [comment]
Giving it a test. Thanks!
