### ISSUE TITLE
Search fails if a task title has more than 1 line

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#97]
**Describe the bug**
When searching for a single word, search will fail to locate tasks that include that word in their title if the title has more than one line

**To Reproduce**
1. Create a task
2. Enter a title
3. Create a newline in the title (e.g. by typing cmd-enter, option-enter, ctl-enter)
4. Enter a second line for the title.
5. Search for any word in the title just entered -- it will not be shown as a search result.  (Doesn't matter if the search term is on the first or second line.)

**Expected behavior**
Search should return all tasks with the search word in the title, regardless of how many lines are in the title.

**Screenshots**

![Screen Shot 2021-11-07 at 11 36 52 AM](https://user-images.githubusercontent.com/85841371/140659472-aa2e4629-4913-4fbb-a820-e3690ee9722b.png)

**Desktop (please complete the following information):**
OS: OSX 10.14.6, Mojave
Stacks Version 1.5.6

**Comment by synapse** [comment]
Hey @mbrock321 this should be fixed in the latest beta version [here](https://github.com/stacks-task-manager/stacks/releases/tag/v1.6.0-b5) available soon in the next public release

**Comment by synapse** [comment]
Hey @mbrock321 this should also be fixed as of 1.6

**Comment by mbrock321** [comment]
Thank-you, yes -- seems to be fixed when I test it.
